// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zhban.proto

package zhban

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DataRequestKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataRequestKey) Reset()         { *m = DataRequestKey{} }
func (m *DataRequestKey) String() string { return proto.CompactTextString(m) }
func (*DataRequestKey) ProtoMessage()    {}
func (*DataRequestKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_667de6062ce961f1, []int{0}
}

func (m *DataRequestKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataRequestKey.Unmarshal(m, b)
}
func (m *DataRequestKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataRequestKey.Marshal(b, m, deterministic)
}
func (m *DataRequestKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataRequestKey.Merge(m, src)
}
func (m *DataRequestKey) XXX_Size() int {
	return xxx_messageInfo_DataRequestKey.Size(m)
}
func (m *DataRequestKey) XXX_DiscardUnknown() {
	xxx_messageInfo_DataRequestKey.DiscardUnknown(m)
}

var xxx_messageInfo_DataRequestKey proto.InternalMessageInfo

func (m *DataRequestKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DataRequestKey) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DataResponse struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	StatusCode           int64    `protobuf:"varint,2,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataResponse) Reset()         { *m = DataResponse{} }
func (m *DataResponse) String() string { return proto.CompactTextString(m) }
func (*DataResponse) ProtoMessage()    {}
func (*DataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_667de6062ce961f1, []int{1}
}

func (m *DataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataResponse.Unmarshal(m, b)
}
func (m *DataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataResponse.Marshal(b, m, deterministic)
}
func (m *DataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataResponse.Merge(m, src)
}
func (m *DataResponse) XXX_Size() int {
	return xxx_messageInfo_DataResponse.Size(m)
}
func (m *DataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DataResponse proto.InternalMessageInfo

func (m *DataResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *DataResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func init() {
	proto.RegisterType((*DataRequestKey)(nil), "zhban.DataRequestKey")
	proto.RegisterType((*DataResponse)(nil), "zhban.DataResponse")
}

func init() { proto.RegisterFile("zhban.proto", fileDescriptor_667de6062ce961f1) }

var fileDescriptor_667de6062ce961f1 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xae, 0xca, 0x48, 0x4a,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x4c, 0xb8, 0xf8, 0x5c,
	0x12, 0x4b, 0x12, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0xbc, 0x53, 0x2b, 0x85, 0x04, 0xb8,
	0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x90, 0x48, 0x69,
	0x51, 0x8e, 0x04, 0x13, 0x44, 0xa4, 0xb4, 0x28, 0x47, 0xc9, 0x89, 0x8b, 0x07, 0xa2, 0xab, 0xb8,
	0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x88, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x11, 0xaa, 0x09, 0xcc,
	0x16, 0x92, 0xe3, 0xe2, 0x2a, 0x2e, 0x49, 0x2c, 0x29, 0x2d, 0x76, 0xce, 0x4f, 0x49, 0x05, 0x6b,
	0x66, 0x0e, 0x42, 0x12, 0x31, 0x72, 0xe6, 0x62, 0x8d, 0x02, 0x39, 0x41, 0xc8, 0x8a, 0x8b, 0xcb,
	0x3d, 0xb5, 0x04, 0x64, 0x1e, 0xc8, 0x7a, 0x51, 0x3d, 0x88, 0x2b, 0x51, 0x5d, 0x25, 0x25, 0x8c,
	0x22, 0x0c, 0xb1, 0x56, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x19, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0e, 0xa4, 0x05, 0xbe, 0xdb, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZhbanClient is the client API for Zhban service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZhbanClient interface {
	GetDataKey(ctx context.Context, in *DataRequestKey, opts ...grpc.CallOption) (*DataResponse, error)
}

type zhbanClient struct {
	cc *grpc.ClientConn
}

func NewZhbanClient(cc *grpc.ClientConn) ZhbanClient {
	return &zhbanClient{cc}
}

func (c *zhbanClient) GetDataKey(ctx context.Context, in *DataRequestKey, opts ...grpc.CallOption) (*DataResponse, error) {
	out := new(DataResponse)
	err := c.cc.Invoke(ctx, "/zhban.Zhban/GetDataKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZhbanServer is the server API for Zhban service.
type ZhbanServer interface {
	GetDataKey(context.Context, *DataRequestKey) (*DataResponse, error)
}

// UnimplementedZhbanServer can be embedded to have forward compatible implementations.
type UnimplementedZhbanServer struct {
}

func (*UnimplementedZhbanServer) GetDataKey(ctx context.Context, req *DataRequestKey) (*DataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataKey not implemented")
}

func RegisterZhbanServer(s *grpc.Server, srv ZhbanServer) {
	s.RegisterService(&_Zhban_serviceDesc, srv)
}

func _Zhban_GetDataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataRequestKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZhbanServer).GetDataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/zhban.Zhban/GetDataKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZhbanServer).GetDataKey(ctx, req.(*DataRequestKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _Zhban_serviceDesc = grpc.ServiceDesc{
	ServiceName: "zhban.Zhban",
	HandlerType: (*ZhbanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDataKey",
			Handler:    _Zhban_GetDataKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "zhban.proto",
}
